name: "♨️ Send email - Production"

on:
  workflow_dispatch:

jobs:
  send-email-for-all-users:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          tools: composer:v2

      - name: Install Composer dependencies
        run: |
          cd src
          composer install --no-progress --optimize-autoloader --quiet

      - name: Import BOTTOM_CONTENT_HTML and TOP_CONTENT_HTML into env
        shell: bash
        run: |
          cd src
          echo "BOTTOM_CONTENT_HTML=$(cat BOTTOM_CONTENT_HTML.txt)" >> $GITHUB_ENV
          echo "TOP_CONTENT_HTML=$(cat TOP_CONTENT_HTML.txt)" >> $GITHUB_ENV

      - name: Run script
        run: php src/send_newsletter.php
        env:
          PAKAT_SMTP_USERNAME: ${{ secrets.PAKAT_SMTP_USERNAME }}
          PAKAT_SMTP_PASSWORD: ${{ secrets.PAKAT_SMTP_PASSWORD }}
          PAKAT_API_KEY:       ${{ secrets.PAKAT_API_KEY }}
          BOTTOM_CONTENT_HTML: ${{ env.BOTTOM_CONTENT_HTML }}
          TOP_CONTENT_HTML:    ${{ env.TOP_CONTENT_HTML }}
          SEND_ENV:            "production"
          IS_DARK:             "false"

      - name: Commit Archive file
        run: |
          git config --local user.email "ohmydevops@gmail.com"
          git config --local user.name "ohmydevops"
          git add -A
          git commit -m "Add Archive"

      - name: Push Archive file
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
