name: "just-for-test"

on:
  workflow_dispatch:

jobs:
  sample:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Show time
        run: TZ=Asia/Tehran date
